---
passwordEnvVar: AUTOMATIONPASSWORD
keepassFile: C:/confidential/db.kdbx
logRoot: C:/logs
logDelimiter: ","
suppressDelimiter: "|"
fileproc_referenceFile: C:/reference/directorymonitoring.csv
fileproc_referenceDelimiter: ","
archiveDirName: Archive
